name: Test

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / ActionMailer ${{ matrix.actionmailer }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.4", "4.0"]
        actionmailer: ["8.0", "8.1"]

    env:
      BUNDLE_GEMFILE: gemfiles/actionmailer_${{ matrix.actionmailer }}.gemfile

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
